### ISSUE TITLE
(Purpur 1.20.4) java.lang.NoSuchFieldError: B

### ISSUE THREAD

**Issue by tatsbruh** [Outspending/BiomesAPI#6]
Using the AmbientParticle setting in the CustomBiome builder causes a crash of  java.lang.NoSuchFieldError: B
Im using Purpur server in the 1.20.4 version, only using my own plugin and FAWE (FastAsyncWorldEdit)

The code is literally the example code that is located in the wiki.
CODE:
CustomBiome biome = CustomBiome.builder() // Creates a new biome builder
        .resourceKey(BiomeResourceKey.of("test", "custombiome")) // Resource key for the biome aka "test:custombiome" (These cannot be registered twice, the resource keys MUST be different than other biomes.)
        .particleRenderer(ParticleRenderer.of(AmbientParticle.CLOUD, 0.001F)) // Ambient Particles for the biome (Not Required)
        .settings(BiomeSettings.builder() // Biome settings (Required, default settings are used if not provided)
                .depth(0.1F) // Depth of the biome (Required, default is 0.1F)
                .scale(0.2F) // Scale of the biome (Required, default is 0.2F)
                .temperature(0.3F) // Temperature of the biome (Required, default of 0.3F)
                .downfall(0.4F) // Downfall of the biome (Required, default is 0.4F)
                .modifier(BiomeTempModifier.NONE) // Temperature modifier of the biome (Required, default is NONE)
                .build())
        .fogColor("#db4929") // Fog color of the biome (Required)
        .foliageColor("#22c1c8") // Foliage color of the biome (Not Required)
        .skyColor("#c8227d") // Sky color of the biome (Required)
        .waterColor("#c82222") // Water color of the biome (Required)
        .waterFogColor("#b9de2e") // Water fog color of the biome (Required)
        .grassColor("#40df8b") // Grass color of the biome (Not Required)
        .build();
        
        
ERROR LOG:
[19:52:18] [Server thread/ERROR]: Error occurred while enabling TLL3 v1.0-alpha (Is it up to date?)
java.lang.NoSuchFieldError: B
	at me.outspending.biomesapi.renderer.AmbientParticle.<clinit>(AmbientParticle.java:52) ~[TLL3-1.0-alpha.jar:?]
	at com.tll3.Misc.World.Biomes.<clinit>(Biomes.java:17) ~[TLL3-1.0-alpha.jar:?]
	at com.tll3.TLL3.onEnable(TLL3.java:39) ~[TLL3-1.0-alpha.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.4.jar:git-Purpur-"544a2b6"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-"544a2b6"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651) ~[purpur-1.20.4.jar:git-Purpur-"544a2b6"]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562) ~[purpur-1.20.4.jar:git-Purpur-"544a2b6"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.4.jar:git-Purpur-"544a2b6"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.20.4.jar:git-Purpur-"544a2b6"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.4.jar:git-Purpur-"544a2b6"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1148) ~[purpur-1.20.4.jar:git-Purpur-"544a2b6"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-"544a2b6"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	
FULL SERVER LOG:        
[2024-02-10-1.log](https://github.com/Outspending/BiomesAPI/files/14255271/2024-02-10-1.log)

**Comment by Outspending** [comment]
Hello! Sorry for the long wait, i will look into this error. Hopefully will be fixed in `0.1.0`. Thank you ❤️ 

EDIT: I figured out the issue, it will be fixed in the next update. Again, so sorry for the long wait 🙏

**Comment by tatsbruh** [comment]
Just realized that you answered the issue, thanks! Really excited for next update :D
